# This is a basic workflow to help you get started with Actions

name: Build flashrom

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # Run every day at midnight EST
    - cron: "0 5 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    defaults:
      run:
        shell: msys2 {0}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: make zip mingw-w64-x86_64-pkgconf mingw-w64-x86_64-libusb mingw-w64-x86_64-libftdi mingw-w64-x86_64-gcc
      - uses: actions/checkout@v2
        with:
          repository: 'flashrom/flashrom'
      - name: build
        run: |
          make
          zip flashrom flashrom.exe C:\msys64\mingw64\bin\libusb-1.0.dll C:\msys64\mingw64\bin\libftdi1.dll
      - id: commit-hash
        run: echo "::set-output name=hash::${git rev-parse --short HEAD}"
      - id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-name: master
          release-name: Flashrom ${{ steps.commit-hash.outputs.hash }}
          owner: flashrom
          repo: flashrom
          commitish: ${{ steps.commit-hash.outputs.hash }}
          prerelease: true
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./flashrom.zip
          asset_name: flashrom.zip
          asset_content_type: application/zip
            
