# This is a basic workflow to help you get started with Actions

name: Build flashrom

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # Run every day at midnight EST
    - cron: "0 5 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    defaults:
      run:
        shell: msys2 {0}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git unzip make mingw-w64-x86_64-pkgconf mingw-w64-x86_64-libusb mingw-w64-x86_64-libftdi mingw-w64-x86_64-gcc
      - uses: actions/checkout@v2
        with:
          repository: 'flashrom/flashrom'
      - name: build
        run: |
          make
